### ISSUE TITLE
Template README.md for the operators

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/operator-templating#152]
Their should be the option to specify a single line introduction for the specific operator (e.g. `This is a Kubernetes Operator to provision and inject secrets for Kubernetes pods. Compared to Kubernetes' native secret mounts, this permits secrets to be selected dynamically based on properties of the Pod.`)
After that something like the following should follow
```
The documentation for this operator can be found at https://docs.stackable.tech/{placeholder}-operator/stable/index.html.
The documentation for all Stackable products can be found at https://docs.stackable.tech/.
```
I would be great if we could add a link to the nigthly integration-tests Jenkins status.

**Comment by vsupalov** [comment]
Bumping this issue, because having templated READMEs for all operators which look closer to [this](https://github.com/datahub-project/datahub) or [this](https://github.com/CrunchyData/postgres-operator) would look way way better than the minimal READMEs we have right now.

Every single README can be seen as a landing page, conveying quality and competency, and inviting the visitor into the stackable ecosystem. It would take a very manageable amount of effort to get our READMEs closer to the above examples, and do a significantly better job at representing our products.

**Comment by fhennig** [comment]
I agree on making the READMEs more landingpage-y and adding all this fancy stuff (logo, community links, etc).

I'm not very happy about templating everywhere, but there would be a lot of duplicate content across operators and templating might make sense.

our current templating mechanism does not permit partial templating of files (which is something I've been annoyed with for a while too), we'd need to extend this.

**Comment by vsupalov** [comment]
Closing this issue, as it has served its purpose.

An epic was created from it https://github.com/stackabletech/issues/issues/273

It was listed as the final issue in that epic, but has been replaced by https://github.com/stackabletech/issues/issues/292
