### ISSUE TITLE
Fix to regenerate charts on MacOS out of the box

### ISSUE THREAD

**Issue by Maleware** [stackabletech/operator-templating#244]
Currently we have the line: 
`version:`
`yq eval -i ".version = \"${VERSION}\" | .appVersion = \"${VERSION}\"" /dev/stdin < "deploy/helm/${OPERATOR_NAME}/Chart.yaml"`
	
although this was introduced to fix for yq from snap, this causes issues for developers on MacOS.

To help MacOS developers, we want to fix that.

**Comment by vsupalov** [comment]
+1. Here is a link to the moment the fix for [snap-distributed yq](https://github.com/stackabletech/operator-templating/blame/ea78dbf51e5c4ab8fe0578b4f286a4f064f7b97f/template/Makefile.j2#L47) was introduced.

It does not seem like `/dev/stdin` can be used this way on MacOS.

Not verified, but removing `/dev/stdin < ` could be a sufficient cross-platform fix. Probably breaking snap compatibility though.

**Comment by Maleware** [comment]
Fixed by https://github.com/stackabletech/operator-templating/pull/245

Will be merged post release.
